/**
 * Apple Health Permissions
 */

export const Permissions = {
    DateOfBirth: 'DateOfBirth',
    BiologicalSex: 'BiologicalSex',
    Height: 'Height',
    Weight: 'Weight',
    BodyMass: 'BodyMass',
    BodyFatPercentage: 'BodyFatPercentage',
    BodyMassIndex: 'BodyMassIndex',
    LeanBodyMass: 'LeanBodyMass',
    Steps: 'Steps',
    StepCount: 'StepCount',
    DistanceWalkingRunning: 'DistanceWalkingRunning',
    DistanceCycling: 'DistanceCycling',
    BasalEnergyBurned: 'BasalEnergyBurned',
    ActiveEnergyBurned: 'ActiveEnergyBurned',
    FlightsClimbed: 'FlightsClimbed',
    NikeFuel: 'NikeFuel',
    AppleExerciseTime: 'AppleExerciseTime',
    DietaryEnergy: 'DietaryEnergy',
    HeartRate: 'HeartRate',
    BodyTemperature: 'BodyTemperature',
    BloodPressureSystolic: 'BloodPressureSystolic',
    BloodPressureDiastolic: 'BloodPressureDiastolic',
    RespiratoryRate: 'RespiratoryRate',
    BloodGlucose: 'BloodGlucose',
    SleepAnalysis: 'SleepAnalysis',
    MindfulSession: 'MindfulSession',
};

/*
export const Permissions = {
    ActiveEnergyBurned: 'ActiveEnergyBurned',
    AppleExerciseTime: 'AppleExerciseTime',
    BasalEnergyBurned: 'BasalEnergyBurned',
    BiologicalSex: 'BiologicalSex',
    BloodGlucose: 'BloodGlucose',
    BloodPressureDiastolic: 'BloodPressureDiastolic',
    BloodPressureSystolic: 'BloodPressureSystolic',
    BodyFatPercentage: 'BodyFatPercentage',
    BodyMass: 'BodyMass',
    BodyMassIndex: 'BodyMassIndex',
    BodyTemperature: 'BodyTemperature',
    DateOfBirth: 'DateOfBirth',
    Biotin: 'Biotin',
    Caffeine: 'Caffeine',
    Calcium: 'Calcium',
    Carbohydrates: 'Carbohydrates',
    Chloride: 'Chloride',
    Cholesterol: 'Cholesterol',
    Copper: 'Copper',
    EnergyConsumed: 'EnergyConsumed',
    FatMonounsaturated: 'FatMonounsaturated',
    FatPolyunsaturated: 'FatPolyunsaturated',
    FatSaturated: 'FatSaturated',
    FatTotal: 'FatTotal',
    Fiber: 'Fiber',
    Folate: 'Folate',
    Iodine: 'Iodine',
    Iron: 'Iron',
    Magnesium: 'Magnesium',
    Manganese: 'Manganese',
    Molybdenum: 'Molybdenum',
    Niacin: 'Niacin',
    PantothenicAcid: 'PantothenicAcid',
    Phosphorus: 'Phosphorus',
    Potassium: 'Potassium',
    Protein: 'Protein',
    Riboflavin: 'Riboflavin',
    Selenium: 'Selenium',
    Sodium: 'Sodium',
    Sugar: 'Sugar',
    Thiamin: 'Thiamin',
    VitaminA: 'VitaminA',
    VitaminB12: 'VitaminB12',
    VitaminB6: 'VitaminB6',
    VitaminC: 'VitaminC',
    VitaminD: 'VitaminD',
    VitaminE: 'VitaminE',
    VitaminK: 'VitaminK',
    Zinc: 'Zinc',
    Water: 'Water',
    DistanceCycling: 'DistanceCycling',
    DistanceWalkingRunning: 'DistanceWalkingRunning',
    FlightsClimbed: 'FlightsClimbed',
    HeartRate: 'HeartRate',
    Height: 'Height',
    LeanBodyMass: 'LeanBodyMass',
    MindfulSession: 'MindfulSession',
    NikeFuel: 'NikeFuel',
    RespiratoryRate: 'RespiratoryRate',
    SleepAnalysis: 'SleepAnalysis',
    StepCount: 'StepCount',
    Steps: 'Steps',
    Weight: 'Weight',
};
*/